/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./*.jsx",
    "./pages/**/*.{js,jsx}",
    "./components/**/*.{js,jsx}",
    "./hooks/**/*.{js,jsx}",
    "./store/**/*.{js,jsx}",
    "./utils/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary": "#243600",
        "on-secondary-fixed": "#151d19",
        "on-secondary": "#29322d",
        "outline": "#8e9380",
        "on-primary-fixed": "#141f00",
        "surface-tint": "#aed366",
        "primary-container": "#c9f07e",
        "error": "#ffb4ab",
        "surface-container": "#1e201f",
        "surface-bright": "#383a38",
        "on-secondary-fixed-variant": "#404943",
        "background": "#121413",
        "surface-dim": "#121413",
        "on-surface-variant": "#c4c9b5",
        "error-container": "#93000a",
        "surface-container-low": "#1a1c1b",
        "on-error-container": "#ffdad6",
        "inverse-on-surface": "#2f3130",
        "primary-fixed": "#c9f07e",
        "on-surface": "#e2e3e0",
        "primary-fixed-dim": "#aed366",
        "tertiary-container": "#e1e3e1",
        "on-tertiary": "#2e3130",
        "surface-container-high": "#282a29",
        "tertiary-fixed": "#e1e3e1",
        "secondary": "#bfc9c2",
        "tertiary-fixed-dim": "#c5c7c5",
        "inverse-primary": "#496800",
        "secondary-fixed-dim": "#bfc9c2",
        "surface": "#121413",
        "secondary-fixed": "#dbe5dd",
        "surface-variant": "#333534",
        "on-primary-fixed-variant": "#364e00",
        "on-primary-container": "#4f6e04",
        "surface-container-lowest": "#0d0f0e",
        "on-tertiary-fixed-variant": "#444746",
        "surface-container-highest": "#333534",
        "on-background": "#e2e3e0",
        "primary": "#ffffff",
        "inverse-surface": "#e2e3e0",
        "on-error": "#690005",
        "tertiary": "#ffffff",
        "on-tertiary-fixed": "#191c1b",
        "outline-variant": "#444939",
        "on-tertiary-container": "#626563",
        "on-secondary-container": "#aeb7b0",
        "secondary-container": "#404943",
      },
      fontFamily: {
        syne: ["Syne"],
        inter: ["Inter"],
        cursive: ['"Dancing Script"', "cursive"],
        "display-lg": ["Syne"],
        "headline-lg-mobile": ["Syne"],
        "headline-md": ["Syne"],
        "body-md": ["Inter"],
        "display-md": ["Syne"],
        handwrite: ['"Caveat"', "cursive"],
        "body-lg": ["Inter"],
        "headline-lg": ["Syne"],
        "label-md": ["Inter"],
        "label-sm": ["Inter"],
      },
      fontSize: {
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-md": ["48px", { lineHeight: "1.1", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "1.2", letterSpacing: "0.08em", fontWeight: "600" }],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
}